import { WheelSegment, WheelTheme } from '../types';

export const PRESET_THEMES: Record<string, WheelTheme> = {
  'btn-housing-expo': {
    id: 'btn-housing-expo',
    name: 'BTN Housing Expo 2026',
    headerBrand: 'btn',
    headerSubtitle: 'Roda Undian Expo Perumahan',
    tagline: 'Putar & Menangkan Hadiah Eksklusif Expo',
    bgGradient: 'from-slate-900 via-[#0B1120] to-[#0F172A]',
    wheelRimColor: '#ffffff',
    wheelOuterBorder: '#e2e8f0',
    footerTitle: 'DANANTARA HOUSING PROPERTY SHOWCASE',
    footerSubtitle: 'INDONESIA BERDAULAT ADIL DAN MAKMUR',
    brandPrimaryColor: '#0047BA',
    buttonColor: '#E62129',
    patternType: 'batik',
  },
  'btn-housing-expo-1': {
    id: 'btn-housing-expo-1',
    name: 'BTN Housing Expo 2026',
    headerBrand: 'btn',
    headerSubtitle: 'Roda Undian Expo Perumahan',
    tagline: 'Putar & Menangkan Hadiah Eksklusif Expo',
    bgGradient: 'from-slate-900 via-[#0B1120] to-[#0F172A]',
    wheelRimColor: '#ffffff',
    wheelOuterBorder: '#e2e8f0',
    footerTitle: 'DANANTARA HOUSING PROPERTY SHOWCASE',
    footerSubtitle: 'INDONESIA BERDAULAT ADIL DAN MAKMUR',
    brandPrimaryColor: '#0047BA',
    buttonColor: '#E62129',
    patternType: 'batik',
  },
  'tech-bonanza': {
    id: 'tech-bonanza',
    name: 'Festival Gadget & Elektronik',
    headerBrand: 'TECHVERSE',
    headerSubtitle: 'Undian Gadget Unggulan',
    tagline: 'Putar Roda Untuk Dapatkan Gadget Impian',
    bgGradient: 'from-slate-950 via-indigo-950 to-slate-900',
    wheelRimColor: '#6366f1',
    wheelOuterBorder: '#312e81',
    footerTitle: 'TECHVERSE GLOBAL SUMMIT',
    footerSubtitle: 'INOVASI TEKNOLOGI & ELEKTRONIK MASA DEPAN',
    brandPrimaryColor: '#6366f1',
    buttonColor: '#3b82f6',
    patternType: 'geometric',
  },
  'gold-jackpot': {
    id: 'gold-jackpot',
    name: 'Undian Emas & Hadiah Mewah',
    headerBrand: 'ROYAL REWARDS',
    headerSubtitle: 'Roda Keberuntungan Emas',
    tagline: 'Uji Keberuntungan Anda di Roda Emas',
    bgGradient: 'from-amber-950 via-zinc-900 to-black',
    wheelRimColor: '#fbbf24',
    wheelOuterBorder: '#78350f',
    footerTitle: 'ROYAL GRAND REWARDS',
    footerSubtitle: 'HAK ISTIMEWA ANGGOTA VIP',
    brandPrimaryColor: '#f59e0b',
    buttonColor: '#d97706',
    patternType: 'dots',
  },
  'foodie-delight': {
    id: 'foodie-delight',
    name: 'Kuliner & Kafe Pilihan',
    headerBrand: 'BREW & BITES',
    headerSubtitle: 'Voucher Kopi & Makanan Harian',
    tagline: 'Putar Untuk Menangkan Kopi & Pastry Segar',
    bgGradient: 'from-amber-950 via-stone-900 to-black',
    wheelRimColor: '#ffffff',
    wheelOuterBorder: '#fed7aa',
    footerTitle: 'ARTISAN ROASTERS CO.',
    footerSubtitle: 'DISAJIKAN DENGAN CITA RASA TERBAIK',
    brandPrimaryColor: '#ea580c',
    buttonColor: '#ea580c',
    patternType: 'grid',
  },
};

export const PRESET_SEGMENTS: Record<string, WheelSegment[]> = {
  'btn-housing-expo': [
    {
      id: 'btn-1',
      label: 'Free Provisi 0%',
      subtext: '100% Free Provision Fee',
      iconName: 'percent',
      color: '#D92D20', // Crimson Red
      textColor: '#FFFFFF',
      weight: 5,
      rarity: 'epic',
      isLoss: false,
      prizeValue: '100% Free Provision Fee',
      voucherCodeTemplate: 'BTN-PROV0',
      terms: 'Berlaku untuk pengajuan KPR Platinum dan KPR Gaess selama periode pameran.',
      initialQuota: 25,
      wonCount: 0,
    },
    {
      id: 'btn-2',
      label: 'Coffee Voucher',
      subtext: 'Rp 50.000',
      iconName: 'coffee',
      color: '#1D4ED8', // Royal Blue
      textColor: '#FFFFFF',
      weight: 35,
      rarity: 'common',
      isLoss: false,
      prizeValue: 'Rp 50.000',
      voucherCodeTemplate: 'BTN-KOPI',
      terms: 'Berlaku di seluruh tenant cafe Expo selama Housing Expo 2026.',
      initialQuota: 100,
      wonCount: 0,
    },
    {
      id: 'btn-3',
      label: 'Better Luck Next...',
      subtext: 'Belum beruntung',
      iconName: 'frown',
      color: '#D92D20', // Crimson Red
      textColor: '#FFFFFF',
      weight: 25,
      rarity: 'loss',
      isLoss: true,
      terms: 'Terima kasih telah berpartisipasi! Kunjungi booth properti untuk putaran ekstra.',
      unlimitedQuota: true,
      initialQuota: 999999,
      wonCount: 0,
    },
    {
      id: 'btn-4',
      label: 'Diskon KPR 500k',
      subtext: 'Rp 500.000',
      iconName: 'home',
      color: '#1D4ED8', // Royal Blue
      textColor: '#FFFFFF',
      weight: 20,
      rarity: 'rare',
      isLoss: false,
      prizeValue: 'Rp 500.000',
      voucherCodeTemplate: 'BTN-KPR500',
      terms: 'Potongan langsung untuk booking fee pengajuan KPR BTN selama expo.',
      initialQuota: 50,
      wonCount: 0,
    },
    {
      id: 'btn-5',
      label: 'Emas Mini 0.5g',
      subtext: '0.5 Gram Fine Gold (99.9%)',
      iconName: 'award',
      color: '#D92D20', // Crimson Red
      textColor: '#FFFFFF',
      weight: 5,
      rarity: 'legendary',
      isLoss: false,
      prizeValue: '0.5 Gram Fine Gold (99.9%)',
      voucherCodeTemplate: 'BTN-EMAS05',
      terms: 'Dapat ditukarkan di Meja Layanan Utama BTN dengan menunjukkan KTP.',
      initialQuota: 5,
      wonCount: 0,
    },
    {
      id: 'btn-6',
      label: 'Exclusive Tumbler',
      subtext: 'Stainless Thermos',
      iconName: 'gift',
      color: '#1D4ED8', // Royal Blue
      textColor: '#FFFFFF',
      weight: 10,
      rarity: 'common',
      isLoss: false,
      prizeValue: 'Stainless Thermos',
      voucherCodeTemplate: 'BTN-TUMBLER',
      terms: 'Ambil di Counter Merchandise Resmi dengan menunjukkan aplikasi BTN Mobile.',
      initialQuota: 80,
      wonCount: 0,
    },
  ],

  'btn-housing-expo-1': [
    {
      id: 'btn1-1',
      label: 'Voucher MAP 50k',
      subtext: 'Belanja Hemat Rp 50.000',
      iconName: 'ticket',
      color: '#1D4ED8',
      textColor: '#FFFFFF',
      weight: 19,
      rarity: 'common',
      isLoss: false,
      prizeValue: 'Rp 50.000',
      voucherCodeTemplate: 'BTN1-MAP50',
      terms: 'Berlaku di seluruh tenant MAP selama Housing Expo 2026.',
      initialQuota: 19,
      wonCount: 0,
    },
    {
      id: 'btn1-2',
      label: 'Voucher MAP 100k',
      subtext: 'Diskon Gede Rp 100.000',
      iconName: 'ticket',
      color: '#D92D20',
      textColor: '#FFFFFF',
      weight: 10,
      rarity: 'rare',
      isLoss: false,
      prizeValue: 'Rp 100.000',
      voucherCodeTemplate: 'BTN1-MAP100',
      terms: 'Berlaku di seluruh tenant MAP selama Housing Expo 2026.',
      initialQuota: 10,
      wonCount: 0,
    },
    {
      id: 'btn1-3',
      label: 'Voucher Belanja 50k',
      subtext: 'Belanja Hemat Rp 50.000',
      iconName: 'ticket',
      color: '#1D4ED8',
      textColor: '#FFFFFF',
      weight: 10,
      rarity: 'common',
      isLoss: false,
      prizeValue: 'Rp 50.000',
      voucherCodeTemplate: 'BTN1-BELANJA50',
      terms: 'Berlaku di seluruh tenant Belanja selama Housing Expo 2026.',
      initialQuota: 10,
      wonCount: 0,
    },
    {
      id: 'btn1-4',
      label: 'Tumbler',
      subtext: 'Exclusive Thermos',
      iconName: 'gift',
      color: '#D92D20',
      textColor: '#FFFFFF',
      weight: 20,
      rarity: 'rare',
      isLoss: false,
      prizeValue: 'Stainless Thermos',
      voucherCodeTemplate: 'BTN1-TUMBLER',
      terms: 'Ambil di Counter Merchandise Resmi dengan menunjukkan aplikasi BTN Mobile.',
      initialQuota: 20,
      wonCount: 0,
    },
    {
      id: 'btn1-5',
      label: 'Diffuser',
      subtext: 'Aroma Terapi Eksklusif',
      iconName: 'sparkles',
      color: '#1D4ED8',
      textColor: '#FFFFFF',
      weight: 10,
      rarity: 'epic',
      isLoss: false,
      prizeValue: 'Diffuser Eksklusif',
      voucherCodeTemplate: 'BTN1-DIFFUSER',
      terms: 'Ambil di Counter Merchandise Resmi dengan menunjukkan aplikasi BTN Mobile.',
      initialQuota: 10,
      wonCount: 0,
    },
    {
      id: 'btn1-6',
      label: 'Coba Lagi',
      subtext: 'Belum Beruntung',
      iconName: 'frown',
      color: '#334155',
      textColor: '#FFFFFF',
      weight: 45,
      rarity: 'loss',
      isLoss: true,
      terms: 'Belum beruntung di putaran ini. Kunjungi booth properti untuk putaran ekstra.',
      unlimitedQuota: true,
      initialQuota: 999999,
      wonCount: 0,
    },
    {
      id: 'btn1-7',
      label: 'TWS',
      subtext: 'True Wireless Audio',
      iconName: 'award',
      color: '#D92D20',
      textColor: '#FFFFFF',
      weight: 4,
      rarity: 'legendary',
      isLoss: false,
      prizeValue: 'TWS Earphone',
      voucherCodeTemplate: 'BTN1-TWS',
      terms: 'Ambil di Counter Merchandise Resmi dengan menunjukkan aplikasi BTN Mobile.',
      initialQuota: 4,
      wonCount: 0,
    },
    {
      id: 'btn1-8',
      label: 'Earphone',
      subtext: 'Earphone Premium',
      iconName: 'award',
      color: '#1D4ED8',
      textColor: '#FFFFFF',
      weight: 2,
      rarity: 'legendary',
      isLoss: false,
      prizeValue: 'Earphone Premium',
      voucherCodeTemplate: 'BTN1-EARPHONE',
      terms: 'Ambil di Counter Merchandise Resmi dengan menunjukkan aplikasi BTN Mobile.',
      initialQuota: 2,
      wonCount: 0,
    },
  ],

  'tech-bonanza': [
    {
      id: 'tech-1',
      label: 'iPhone 15 Pro',
      subtext: '128GB Titanium',
      iconName: 'smartphone',
      color: '#6366F1',
      textColor: '#FFFFFF',
      weight: 1,
      rarity: 'legendary',
      isLoss: false,
      prizeValue: 'Senilai Rp 18.000.000',
      voucherCodeTemplate: 'TECH-IPHONE15',
      terms: 'Hadiah Utama. Klaim di panggung utama dengan verifikasi KTP.',
      initialQuota: 10,
      wonCount: 0,
    },
    {
      id: 'tech-2',
      label: 'Earpods Nirkabel',
      subtext: 'True Wireless Audio ANC',
      iconName: 'award',
      color: '#EC4899',
      textColor: '#FFFFFF',
      weight: 5,
      rarity: 'epic',
      isLoss: false,
      prizeValue: 'Senilai Rp 1.500.000',
      voucherCodeTemplate: 'TECH-EARPODS',
      terms: 'Tunjukkan voucher di booth audio resmi untuk mengambil produk.',
      initialQuota: 3,
      wonCount: 0,
    },
    {
      id: 'tech-3',
      label: 'Coba Lagi',
      subtext: 'Kesempatan Berikutnya',
      iconName: 'frown',
      color: '#334155',
      textColor: '#FFFFFF',
      weight: 40,
      rarity: 'loss',
      isLoss: true,
      terms: 'Belum beruntung di putaran ini. Scan QR merchant untuk putaran tambahan.',
      unlimitedQuota: true,
      initialQuota: 999999,
      wonCount: 0,
    },
    {
      id: 'tech-4',
      label: 'Powerbank 20.000mAh',
      subtext: 'Fast Charging 65W',
      iconName: 'zap',
      color: '#8B5CF6',
      textColor: '#FFFFFF',
      weight: 15,
      rarity: 'rare',
      isLoss: false,
      prizeValue: 'Powerbank 65W GaN',
      voucherCodeTemplate: 'TECH-PWR65',
      terms: 'Klaim di Booth Gadget 4B. Garansi resmi 1 tahun.',
      initialQuota: 20,
      wonCount: 0,
    },
    {
      id: 'tech-5',
      label: 'Voucher Belanja 100rb',
      subtext: 'Semua Aksesoris Gadget',
      iconName: 'ticket',
      color: '#06B6D4',
      textColor: '#FFFFFF',
      weight: 24,
      rarity: 'common',
      isLoss: false,
      prizeValue: 'Rp 100.000',
      voucherCodeTemplate: 'TECH-BELANJA100',
      terms: 'Tanpa minimum pembelian. Berlaku selama festival.',
      initialQuota: 100,
      wonCount: 0,
    },
    {
      id: 'tech-6',
      label: 'Kupon Diskon 20%',
      subtext: 'Diskon Belanja Storewide',
      iconName: 'percent',
      color: '#0EA5E9',
      textColor: '#FFFFFF',
      weight: 15,
      rarity: 'common',
      isLoss: false,
      prizeValue: 'Diskon 20%',
      voucherCodeTemplate: 'TECH-DISKON20',
      terms: 'Maksimal potongan Rp 200.000 di merchant terdaftar.',
      initialQuota: 150,
      wonCount: 0,
    },
  ],

  'gold-jackpot': [
    {
      id: 'gold-1',
      label: 'Logam Mulia 5 Gram',
      subtext: 'Emas Murni 99.99%',
      iconName: 'sparkles',
      color: '#B45309',
      textColor: '#FEF3C7',
      weight: 1,
      rarity: 'legendary',
      isLoss: false,
      prizeValue: '5 Gram Emas Murni',
      voucherCodeTemplate: 'ROYAL-EMAS5G',
      terms: 'Hadiah Jackpot Utama. Klaim di meja customer service VIP.',
      initialQuota: 2,
      wonCount: 0,
    },
    {
      id: 'gold-2',
      label: 'Voucher Belanja 500rb',
      subtext: 'Belanja Bebas',
      iconName: 'dollar-sign',
      color: '#D97706',
      textColor: '#FFFFFF',
      weight: 14,
      rarity: 'epic',
      isLoss: false,
      prizeValue: 'Rp 500.000',
      voucherCodeTemplate: 'ROYAL-CASH500',
      terms: 'Dapat digunakan di seluruh tenant pameran.',
      initialQuota: 25,
      wonCount: 0,
    },
    {
      id: 'gold-3',
      label: 'Coba Lagi',
      subtext: 'Putar lagi nanti',
      iconName: 'frown',
      color: '#27272A',
      textColor: '#A1A1AA',
      weight: 40,
      rarity: 'loss',
      isLoss: true,
      terms: 'Belum beruntung kali ini. Kumpulkan poin untuk putaran tambahan.',
      unlimitedQuota: true,
      initialQuota: 999999,
      wonCount: 0,
    },
    {
      id: 'gold-4',
      label: 'Voucher Makan Mewah',
      subtext: 'Buffet Dinner 2 Orang',
      iconName: 'award',
      color: '#F59E0B',
      textColor: '#18181B',
      weight: 15,
      rarity: 'rare',
      isLoss: false,
      prizeValue: 'Paket Makan Berdua',
      voucherCodeTemplate: 'ROYAL-MAKAN',
      terms: 'Berlaku di resto hotel rekanan.',
      initialQuota: 15,
      wonCount: 0,
    },
    {
      id: 'gold-5',
      label: 'Voucher Belanja 100rb',
      subtext: 'Voucher Langsung Pakai',
      iconName: 'ticket',
      color: '#B45309',
      textColor: '#FEF3C7',
      weight: 20,
      rarity: 'common',
      isLoss: false,
      prizeValue: 'Rp 100.000',
      voucherCodeTemplate: 'ROYAL-VOUCHER100',
      terms: 'Satu voucher per transaksi.',
      initialQuota: 80,
      wonCount: 0,
    },
    {
      id: 'gold-6',
      label: 'Merchandise VIP',
      subtext: 'Paket Eksklusif',
      iconName: 'gift',
      color: '#78350F',
      textColor: '#FEF3C7',
      weight: 10,
      rarity: 'rare',
      isLoss: false,
      prizeValue: 'VIP Gift Set',
      voucherCodeTemplate: 'ROYAL-GIFT',
      terms: 'Ambil di Meja Informasi VIP.',
      initialQuota: 50,
      wonCount: 0,
    },
  ],

  'foodie-delight': [
    {
      id: 'food-1',
      label: 'Kopi Gratis',
      subtext: 'Pilihan Minuman Bebas',
      iconName: 'coffee',
      color: '#C2410C',
      textColor: '#FFFFFF',
      weight: 35,
      rarity: 'common',
      isLoss: false,
      prizeValue: '1 Cup Kopi Pilihan',
      voucherCodeTemplate: 'KAFE-KOPIGRATIS',
      terms: 'Pilih Latte, Cappuccino, Americano, atau Kopi Susu Gula Aren.',
      initialQuota: 150,
      wonCount: 0,
    },
    {
      id: 'food-2',
      label: 'Coba Lagi',
      subtext: 'Semoga beruntung berikutnya',
      iconName: 'frown',
      color: '#78716C',
      textColor: '#FFFFFF',
      weight: 20,
      rarity: 'loss',
      isLoss: true,
      terms: 'Setiap transaksi makanan memberikan kesempatan putar roda!',
      unlimitedQuota: true,
      initialQuota: 999999,
      wonCount: 0,
    },
    {
      id: 'food-3',
      label: 'Gratis Croissant',
      subtext: 'Butter Pastry Segar',
      iconName: 'shopping-bag',
      color: '#D97706',
      textColor: '#FFFFFF',
      weight: 20,
      rarity: 'common',
      isLoss: false,
      prizeValue: 'Almond / Butter Croissant',
      voucherCodeTemplate: 'KAFE-CROISSANT',
      terms: 'Berlaku selama persediaan harian masih ada.',
      initialQuota: 75,
      wonCount: 0,
    },
    {
      id: 'food-4',
      label: 'Diskon 50% Total Menu',
      subtext: 'Maksimal Diskon 50rb',
      iconName: 'percent',
      color: '#EA580C',
      textColor: '#FFFFFF',
      weight: 5,
      rarity: 'legendary',
      isLoss: false,
      prizeValue: 'Diskon 50% Makan di Tempat',
      voucherCodeTemplate: 'KAFE-DISKON50',
      terms: 'Hanya berlaku untuk santap di tempat (Dine-in).',
      initialQuota: 10,
      wonCount: 0,
    },
    {
      id: 'food-5',
      label: 'Beli 1 Gratis 1',
      subtext: 'Minuman Segar',
      iconName: 'gift',
      color: '#9A3412',
      textColor: '#FFFFFF',
      weight: 15,
      rarity: 'rare',
      isLoss: false,
      prizeValue: 'Buy 1 Get 1 Minuman',
      voucherCodeTemplate: 'KAFE-BOGO',
      terms: 'Minuman gratis dengan nilai sama atau lebih rendah.',
      initialQuota: 60,
      wonCount: 0,
    },
    {
      id: 'food-6',
      label: 'Kotak Kue Spesial',
      subtext: '4 Pcs Aneka Kue',
      iconName: 'award',
      color: '#B45309',
      textColor: '#FFFFFF',
      weight: 5,
      rarity: 'epic',
      isLoss: false,
      prizeValue: 'Box 4 Pcs Artisan Cookies',
      voucherCodeTemplate: 'KAFE-COOKIES',
      terms: 'Dipanggang segar setiap hari.',
      initialQuota: 20,
      wonCount: 0,
    },
  ],
};

